# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "1220d4c5bfcdbf2fe3b074650f5f827731a1e1d6dfd8a0adbfbbf405e08c5adcab4a";
    path = fetchzip {
      url = "https://github.com/tree-sitter/tree-sitter-c/archive/refs/tags/v0.23.4.tar.gz";
      hash = "sha256-nb+CoRbX7RFAGus7USWA1NhAnnkkJ89vIdSN36QmSCE=";
    };
  }
  {
    name = "N-V-__8AABHIEgaTyzPfjgnnCy0dwJiXoDiJFblCkYOJsQvy";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-android-c-api.tar.xz";
      hash = "sha256-DuTRSgotMJN6/OWJ+WEcYMsQKMh5OSSEWyqpBrwEK0Q=";
    };
  }
  {
    name = "N-V-__8AAC3KCQZMd5ea2CkcbjldaVqCT7BT_9_rLMId6V__";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-aarch64-android-c-api.tar.xz";
      hash = "sha256-2uApjXYj+xX6nEGD6kS98I7jjGZaVMc9vxfBZ9aUDDw=";
    };
  }
  {
    name = "N-V-__8AAG-uVQVEDMsB1ymJzxpHcoiXo1_I3TFnPM5Zjy1i";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-windows-c-api.zip";
      hash = "sha256-HgPapayChuclbw2osBjB8Cbpon8jE8r+SEx2BHhr6oI=";
    };
  }
  {
    name = "N-V-__8AAGUY3gU6jj2CNJAYb7HiMNVPV1FIcTCI6RSSYwXu";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-aarch64-linux-c-api.tar.xz";
      hash = "sha256-jKuO0aZlPaltOnGY01jcxTkaKF3bgFMalq2zdrAFlag=";
    };
  }
  {
    name = "N-V-__8AALMZ5wXJWW5qY-3MMjTAYR0MusckvzCsmg-69ALH";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-musl-c-api.tar.xz";
      hash = "sha256-3zJsnyeO0nzGF+zA7ALwAo1Kke9urOO7M8aaLYfbH1o=";
    };
  }
  {
    name = "N-V-__8AALUN5AWSEDRulL9u-OJJ-l0_GoT5UFDtGWZayEIq";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-linux-c-api.tar.xz";
      hash = "sha256-I3VLmDMEecQZcF6XdUXK6a+Thd5zp9KhZVjeJGJT/lo=";
    };
  }
  {
    name = "N-V-__8AALundgW-p1ffOnd7bsYyL8SY5OziDUZu7cXio2EL";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-mingw-c-api.zip";
      hash = "sha256-LV5/+VN8oSBFN0cUJDWfS/pNpRPffX3ERGb17PHtq0I=";
    };
  }
  {
    name = "N-V-__8AAM1GMARD6LGQebhVsSZ0uePUoo3Fw5nEO2L764vf";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-aarch64-macos-c-api.tar.xz";
      hash = "sha256-Lwpr8VpalT9IrSKEZFk7dHlJGxoosYCFVDLvpG9hQ80=";
    };
  }
  {
    name = "N-V-__8AAN2cuQadBwMc8zJxv0sMY99Ae1Nc1dZcZAK9b4DZ";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-riscv64gc-linux-c-api.tar.xz";
      hash = "sha256-b40LPvxaBE21Xe1jOAT74t5XRLF8yG0ZNavuaLrHo/A=";
    };
  }
  {
    name = "N-V-__8AANUeXwSPh13TqJCSSFdi87GEcHs8zK6FqE4v_TjB";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-macos-c-api.tar.xz";
      hash = "sha256-mymXnUcLHXQAy85C3F5+Efwg33l1kjWQNuZUl9VXCpY=";
    };
  }
  {
    name = "N-V-__8AAPevngYz99mwT0KQY9my2ax1p6APzgLEJeV4II9U";
    path = fetchzip {
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-s390x-linux-c-api.tar.xz";
      hash = "sha256-TeVGxft0M4KfEVwEYbFGbaw27JcDUjMtHajvnGW+FJ4=";
    };
  }
  {
    name = "tree_sitter-0.25.1-nRPadvxvAQCMGJDUpyLEFZvHCYsjv9ZftBkLoLPSGfGN";
    path = fetchgit {
      url = "https://github.com/bruvduroiu/zig-tree-sitter";
      rev = "f7da93e78a55d75568636b0fe0d059413270c324";
      hash = "sha256-YVU8pz84LwFQWraojeIhqfd/NYVQhfpq3jUkPaJc0DI=";
    };
  }
  {
    name = "tree_sitter-0.26.0-Tw2sRze4CwBXko_uJgxJ1MkugKV8iVAQuPLxNRHrcqab";
    path = fetchgit {
      url = "https://github.com/tree-sitter/tree-sitter";
      rev = "521da2b0a7e8815efbcf1e4b98e5ac16113c5763";
      hash = "sha256-SpM0+BsMrp3OhHJMHGdg1y5j4CdisiOpWsN48aXTIBo=";
    };
  }
]
