name: Pull

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x86_64 ]
        target: [ linux ]
    runs-on: ${{ matrix.os }}
    env:
      ZIG_LOCAL_CACHE_DIR: /zig/local-cache
      ZIG_GLOBAL_CACHE_DIR: /zig/global-cache
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    #
    # - name: Setup cache 
    #   uses: namespacelabs/nscloud-cache-action@v1.2.12
    #   with:
    #     path: |
    #       /nix
    #       /zig

    # Install Nix and use that to run our tests so our environment matches exactly.
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          system = ${{ matrix.arch }}-${{ matrix.target }}

    - run: nix flake check

    - name: Build
      run: nix build
