name: Pull

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [ aarch64 x86_64 ]
        target: [
          linux-gnu,
          linux-musl,
          macos,
          windows-gnu
        ]
    runs-on: ${{ matrix.os }}
    env:
      ZIG_LOCAL_CACHE_DIR: /zig/local-cache
      ZIG_GLOBAL_CACHE_DIR: /zig/global-cache
    steps:
    - name: Checkout code
      uses: actions/checkou@v4

    - name: Setup cache 
      uses: namespacelabs/nscloud-cache-action@v1.2.12
      with:
        path: |
          /nix
          /zig

    # Install Nix and use that to run our tests so our environment matches exactly.
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: nix flake check

    - name: test
      run: nix develop -c zig build --summary all -Dtarget=${{ matrix.arch }}-${{ matrix.target }}

    - name: Build
      run: nix build .#llmstxt-zig
